name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
  - https://raw.githubusercontent.com/atomwrath/menu_viewer/main/packages
dependencies:
  - xeus-python
  - pandas
  - ipywidgets
  - pint
  - openpyxl>=3.1.2
